## bash.rc
export DOTFILES=$HOME/.dotfiles
export OS=`uname`
if [ "$OS" == "Darwin" ]; then
  export DOMAIN='osx'
elif [ -f /etc/centos-release ]; then
  export DOMAIN='centos'
elif [ -f /etc/debian_version ]; then
  export DOMAIN='debian'
  if [ "$(uname -r | grep bone | wc -l)" -ge "1" ]; then
    export BEAGLEBONE_BLACK=1
    export ARM_DEVICE=1
  elif [ "$(uname -m)" == "armv6l" ]; then
    export RASPBERRY_PI=1
    export ARM_DEVICE=1
  fi
else
  export DOMAIN='unknown'
fi


function source_rc() {
  for rc in $1/*; do
    if [ -f $rc ]; then
      source $rc
    fi
  done
}

source_rc $DOTFILES/source
source_rc $DOTFILES/source/domain/$DOMAIN
source_rc $DOTFILES/source/os/$OS
source_rc $DOTFILES/source/host/$HOSTNAME
