#zsh

function source_rc() {
  for rc in $1/*; do
    if [ -f $rc ]; then
      source $rc
    fi
  done
}

source_rc $HOME/.dotfiles/zshrc.d

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
