# Shell integrations generated by third-party CLIs -- the `eval "$(tool init)"`
# family. Loads at 03 so anything here can rely on compinit, which runs in
# 01.completion.zsh.

# fzf -- CTRL-T (paste file paths), CTRL-R (search history), ALT-C (cd into a
# subdirectory), plus the `**<TAB>` fuzzy completion trigger. `fzf --zsh`
# replaced the old ~/.fzf.zsh install script in fzf 0.48, so brew's
# $(brew --prefix)/opt/fzf/install is no longer needed.
#
# CTRL-T's widget passes --reverse, which puts the prompt at the top; CTRL-R's
# does not, so its prompt sits at the bottom with the list growing upward. The
# two keys should not move the box around between them, so --layout=default here
# cancels the --reverse. It works because fzf appends FZF_CTRL_T_OPTS after the
# widget's own options and the last --layout wins.
export FZF_CTRL_T_OPTS="--layout=default"

if command -v fzf >/dev/null; then
  source <(fzf --zsh)
fi

# forgit -- fzf pickers for the git commands that take a file, commit or branch
# argument: add, log, diff, checkout, rebase, stash and so on, each with a
# preview pane. Shell functions plus aliases, sourced rather than eval'd, so it
# lives here beside fzf, which it needs.
#
# Its previews go through `git config core.pager`, i.e. delta, so they pick up
# the terafox feature from ~/.gitconfig like everything else.
#
# forgit defines its aliases unconditionally, replacing whatever is there. Three
# of its defaults are already taken in 02.aliases.zsh -- ga (`git add -A`), gd
# (`git diff`) and glo (`git pull origin`) -- so those three are renamed via the
# forgit_* variables the plugin reads, and the plain versions keep working. The
# other 26 aliases keep forgit's own names. Must be exported before sourcing.
if [[ -r ${HOMEBREW_PREFIX:-/opt/homebrew}/share/forgit/forgit.plugin.zsh ]]; then
  export forgit_add=gfa forgit_log=gfl forgit_diff=gfd
  source "${HOMEBREW_PREFIX:-/opt/homebrew}/share/forgit/forgit.plugin.zsh"
fi
