# Shell integrations generated by third-party CLIs -- the `eval "$(tool init)"`
# family. Loads at 03 so anything here can rely on compinit, which runs in
# 01.completion.zsh.

# fzf -- CTRL-T (paste file paths), CTRL-R (search history), ALT-C (cd into a
# subdirectory), plus the `**<TAB>` fuzzy completion trigger. `fzf --zsh`
# replaced the old ~/.fzf.zsh install script in fzf 0.48, so brew's
# $(brew --prefix)/opt/fzf/install is no longer needed.
if command -v fzf >/dev/null; then
  source <(fzf --zsh)
fi
