" For this file to run, ~/.vimrc should contain:
"" Load the first file named 'vimrc' found in runtimepath
" runtime vimrc

" Allow vim to manage multiple buffers effectively
set hidden

" Increase command history
set history=1000

" case-smart searching
set ignorecase
set smartcase

" set the terminal title
set title

" maintain more context around the cursor
set scrolloff=3

" highlight current line
set cursorline

" Intuitive backspacing in insert mode
set backspace=indent,eol,start

" toggle paste mode with F12, need to paste in code without auto indentation from "indent on"
set pastetoggle=<F12>

" File-type highlighting and configuration.
" Run :filetype (without args) to see what you may have to turn on yourself, or just set them all to be sure.
syntax on
filetype on
filetype plugin on
filetype indent on

" Highlight search terms...
set hlsearch
set incsearch " ...dynamically as they are typed.

" Clipboard compat with system clipboard
set clipboard=unnamed
" map CTRL+C to copy
vmap <C-C> "+y
" map CTRL+V to paste
vmap <C-V> "+p

" Use a mouse!
set mouse=a

" remap command key to ;
nnoremap ; :

" statusline
set laststatus=2
set statusline=%F\ %m\ \ %l/%LL:%cC

" show line numbers
set number

" tabs
" set showtabline=2
set tabstop=4

" navigate between tabs using CTRL+arrows
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

" keep .swp and backups out of the way
set directory=$HOME/.vim/tmp
set backupdir=$HOME/.vim/tmp

" colors (also handles tab/status bar colors)
colo diffsky
" Show syntax highlighting groups for word under cursor
nmap <C-l> :HLT<CR>

" ale linter options
" lint on save only
"let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_delay=1000
" type ALEFix to autofix eslint errors
let g:ale_fixers = {'javascript': ['eslint']}

" always show gutter column
set signcolumn=yes

" custom git gutter sign
let g:gitgutter_sign_modified = '■'

" open file explorer with CTRL+E
map <C-e> :NERDTreeToggle<CR>

" FZF plugin
nnoremap <C-P> :FZF<CR>
let g:fzf_layout = { 'down': '~20%' }
" ensure FZF.vim knows where to find binary installed from homebrew
set rtp+=/usr/local/opt/fzf

" shift+arrow selection
nmap <S-Up> v<Up>
nmap <S-Down> v<Down>
nmap <S-Left> v<Left>
nmap <S-Right> v<Right>
vmap <S-Up> <Up>
vmap <S-Down> <Down>
vmap <S-Left> <Left>
vmap <S-Right> <Right>
imap <S-Up> <Esc>v<Up>
imap <S-Down> <Esc>v<Down>
imap <S-Left> <Esc>v<Left>
imap <S-Right> <Esc>v<Right>
